/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_miniproject.calculator;

/**
 *
 * @author trias
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    Control C = new Control();
    private String Equation = "";
    private Boolean NumberClicked = true;
    private Boolean OperatorClicked = true;
    private Boolean AllowDecimal = false;
    private javax.swing.JButton Operation_Buttons[] = new javax.swing.JButton[5];
    public Frame()
    {
        initComponents();
        Operation_Buttons[0] = Add;
        Operation_Buttons[1] = Subtract;
        Operation_Buttons[2] = Multiply;
        Operation_Buttons[3] = Divide;
        Operation_Buttons[4] = Equals;
        C.SetButtonStatus(Operation_Buttons, false, D_Point, false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Result = new javax.swing.JTextField();
        Seven = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        One = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        D_Point = new javax.swing.JButton();
        Equals = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Subtract = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        CurrentEquation = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        Result.setEditable(false);
        Result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Seven.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });

        Four.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Four.setText("4");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });

        One.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });

        Two.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Two.setText("2");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });

        Eight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Eight.setText("8");
        Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightActionPerformed(evt);
            }
        });

        Five.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Five.setText("5");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });

        Nine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Nine.setText("9");
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });

        Six.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Six.setText("6");
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });

        Three.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Three.setText("3");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });

        Zero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });

        D_Point.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        D_Point.setText(".");
        D_Point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_PointActionPerformed(evt);
            }
        });

        Equals.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Equals.setText("=");
        Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsActionPerformed(evt);
            }
        });

        Divide.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Divide.setText("/");
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });

        Multiply.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Multiply.setText("*");
        Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyActionPerformed(evt);
            }
        });

        Subtract.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Subtract.setText("-");
        Subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractActionPerformed(evt);
            }
        });

        Add.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Add.setText("+");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        ScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        CurrentEquation.setEditable(false);
        CurrentEquation.setColumns(1);
        CurrentEquation.setRows(1);
        ScrollPane.setViewportView(CurrentEquation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Result, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Four, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(One, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Two, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Five, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_Point, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Six, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Three, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Four, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Five, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Six, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(One, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Two, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Three, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_Point, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Clear.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '7';
        CurrentEquation.setText(CurrentEquation.getText() + "7");
    }//GEN-LAST:event_SevenActionPerformed

    private void EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '8';
        CurrentEquation.setText(CurrentEquation.getText() + "8");
    }//GEN-LAST:event_EightActionPerformed

    private void NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '9';
        CurrentEquation.setText(CurrentEquation.getText() + "9");
    }//GEN-LAST:event_NineActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        // TODO add your handling code here:
        OperatorClicked = true;
        if(OperatorClicked)
        {
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, false, D_Point, AllowDecimal);
        Equation += '/';
        CurrentEquation.setText(CurrentEquation.getText() + " / ");
    }//GEN-LAST:event_DivideActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
        // TODO add your handling code here:

        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        };
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '4';
        CurrentEquation.setText(CurrentEquation.getText() + "4");
    }//GEN-LAST:event_FourActionPerformed

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '5';
        CurrentEquation.setText(CurrentEquation.getText() + "5");
    }//GEN-LAST:event_FiveActionPerformed

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '6';
        CurrentEquation.setText(CurrentEquation.getText() + "6");
    }//GEN-LAST:event_SixActionPerformed

    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '1';
        CurrentEquation.setText(CurrentEquation.getText() + "1");
    }//GEN-LAST:event_OneActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '2';
        CurrentEquation.setText(CurrentEquation.getText() + "2");
    }//GEN-LAST:event_TwoActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, true, D_Point, AllowDecimal);
        Equation += '3';
        CurrentEquation.setText(CurrentEquation.getText() + "3");
    }//GEN-LAST:event_ThreeActionPerformed

    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        // TODO add your handling code here:
        OperatorClicked = true;
        if(OperatorClicked)
        {
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, false, D_Point, AllowDecimal);
        Equation += '*';
        CurrentEquation.setText(CurrentEquation.getText() + " * ");
    }//GEN-LAST:event_MultiplyActionPerformed

    private void SubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractActionPerformed
        // TODO add your handling code here:
        OperatorClicked = true;
        if(OperatorClicked)
        {
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, false, D_Point, AllowDecimal);
        Equation += '-';
        CurrentEquation.setText(CurrentEquation.getText() + " - ");
    }//GEN-LAST:event_SubtractActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        OperatorClicked = true;
        if(OperatorClicked)
        {
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, false, D_Point, AllowDecimal);
        Equation += '+';
        CurrentEquation.setText(CurrentEquation.getText() + " + ");
    }//GEN-LAST:event_AddActionPerformed

    private void EqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualsActionPerformed
        // TODO add your handling code here:
        if(Equation.length() != 0)
        {
            Result.setText(C.Equation(Equation));
        }
    }//GEN-LAST:event_EqualsActionPerformed

    private void D_PointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_PointActionPerformed
        // TODO add your handling code here:
        if(AllowDecimal)
        {
            Equation += '.';
            AllowDecimal = false;
            OperatorClicked = false;
            NumberClicked = false;
        }
        C.SetButtonStatus(Operation_Buttons, false, D_Point, AllowDecimal);
        CurrentEquation.setText(CurrentEquation.getText() + ".");
    }//GEN-LAST:event_D_PointActionPerformed

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroActionPerformed
        // TODO add your handling code here:
        if(OperatorClicked)
        {
            NumberClicked = true;
            if(NumberClicked)
            {
                AllowDecimal = true;
            }
        }
        C.SetButtonStatus(Operation_Buttons, false, D_Point, AllowDecimal);
        Equation += '0';
        CurrentEquation.setText(CurrentEquation.getText() + "0");
    }//GEN-LAST:event_ZeroActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        // Reset All
        Equation = "";
        AllowDecimal = false;
        OperatorClicked = true;
        NumberClicked = false;
        C.SetButtonStatus(Operation_Buttons, false, D_Point, AllowDecimal);
        CurrentEquation.setText("");
        Result.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try
        {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarculaLaf());
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JTextArea CurrentEquation;
    private javax.swing.JButton D_Point;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Eight;
    private javax.swing.JButton Equals;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Nine;
    private javax.swing.JButton One;
    private javax.swing.JTextField Result;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Six;
    private javax.swing.JButton Subtract;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JButton Zero;
    // End of variables declaration//GEN-END:variables
}
