/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_miniproject.taskmanager;

import java.time.*;
import java.util.*;
import javax.swing.JOptionPane;


/**
 *
 * @author trias
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    
    Control C = new Control();
    Object SpObj[] = new Object[3];
    public MainForm() {
        initComponents();
        C.LoadExistingTasks(TasksPane);
        SpObj[0] = HoursSpinner.getValue();
        SpObj[1] = MinutesSpinner.getValue();
        SpObj[2] = AMorPM.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        MainScrollpane = new javax.swing.JScrollPane();
        TasksPane = new javax.swing.JTabbedPane();
        AddTasksTab = new javax.swing.JPanel();
        TaskNameLabel = new javax.swing.JLabel();
        TaskDescLabel = new javax.swing.JLabel();
        TaskNameField = new javax.swing.JTextField();
        DescScrollPane = new javax.swing.JScrollPane();
        TaskDescField = new javax.swing.JTextArea();
        AddTasksButton = new javax.swing.JButton();
        DeadlineLabel = new javax.swing.JLabel();
        MonthComboBox = new javax.swing.JComboBox<>();
        DayComboBox = new javax.swing.JComboBox<>();
        YearComboBox = new javax.swing.JComboBox<>();
        MinutesSpinner = new javax.swing.JSpinner();
        HoursSpinner = new javax.swing.JSpinner();
        TimeColonLabel = new javax.swing.JLabel();
        AMorPM = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tasks App");
        setResizable(false);

        TitlePanel.setBackground(new java.awt.Color(48, 48, 48));

        Title.setBackground(new java.awt.Color(12, 12, 12));
        Title.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 108, 0));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Tasks");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        MainScrollpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TasksPane.setBackground(new java.awt.Color(204, 204, 204));
        TasksPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TasksPane.setOpaque(true);

        AddTasksTab.setBackground(new java.awt.Color(42, 42, 42));
        AddTasksTab.setForeground(new java.awt.Color(255, 133, 0));

        TaskNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TaskNameLabel.setForeground(new java.awt.Color(255, 133, 0));
        TaskNameLabel.setText("Task Name: ");
        TaskNameLabel.setVerifyInputWhenFocusTarget(false);

        TaskDescLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TaskDescLabel.setForeground(new java.awt.Color(255, 133, 0));
        TaskDescLabel.setText("Task Description:");

        TaskDescField.setColumns(20);
        TaskDescField.setLineWrap(true);
        TaskDescField.setRows(5);
        TaskDescField.setWrapStyleWord(true);
        DescScrollPane.setViewportView(TaskDescField);

        AddTasksButton.setBackground(new java.awt.Color(27, 27, 27));
        AddTasksButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AddTasksButton.setForeground(new java.awt.Color(255, 157, 0));
        AddTasksButton.setText("Add Task");
        AddTasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTasksButtonActionPerformed(evt);
            }
        });

        DeadlineLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        DeadlineLabel.setForeground(new java.awt.Color(255, 133, 0));
        DeadlineLabel.setText("Deadline:");

        MonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        DayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        YearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        MinutesSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"}));
        MinutesSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        HoursSpinner.setModel(new javax.swing.SpinnerNumberModel(6, 1, 12, 1));

        TimeColonLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        TimeColonLabel.setForeground(new java.awt.Color(255, 133, 0));
        TimeColonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeColonLabel.setText(":");

        AMorPM.setModel(new javax.swing.SpinnerListModel(new String[] {"AM", "PM"}));
        AMorPM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout AddTasksTabLayout = new javax.swing.GroupLayout(AddTasksTab);
        AddTasksTab.setLayout(AddTasksTabLayout);
        AddTasksTabLayout.setHorizontalGroup(
            AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTasksTabLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskNameLabel)
                    .addComponent(TaskDescLabel)
                    .addComponent(DeadlineLabel))
                .addGap(32, 32, 32)
                .addGroup(AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TaskNameField)
                        .addComponent(DescScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AddTasksTabLayout.createSequentialGroup()
                            .addComponent(MonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(YearComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddTasksTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeColonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AMorPM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        AddTasksTabLayout.setVerticalGroup(
            AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTasksTabLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskNameLabel)
                    .addComponent(TaskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskDescLabel)
                    .addComponent(DescScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeadlineLabel))
                .addGap(18, 18, 18)
                .addGroup(AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AddTasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MinutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AMorPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HoursSpinner)
                    .addComponent(TimeColonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(AddTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        TasksPane.addTab("Add New Task", AddTasksTab);

        MainScrollpane.setViewportView(TasksPane);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainScrollpane)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainScrollpane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddTasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTasksButtonActionPerformed
        // TODO add your handling code here:
        // Check For Blank Inputs
        Boolean InputFlag = true;
        Boolean ValidDate = false;
        String TaskName = TaskNameField.getText().trim();
        String TaskDesc = TaskDescField.getText().trim();
        if("".equals(TaskName))
        {
            InputFlag = false;
        }
        if("".equals(TaskDesc))
        {
            InputFlag = false;
        }
        // Check Date
        int Year = Integer.parseInt(YearComboBox.getSelectedItem().toString());
        int Month = MonthComboBox.getSelectedIndex()+1;
        int Day = Integer.parseInt(DayComboBox.getSelectedItem().toString());
        int Hour = Integer.parseInt(HoursSpinner.getValue().toString());
        if("PM".equals(AMorPM.getValue().toString().trim())) { Hour += 12; }
        int Minute = Integer.parseInt(MinutesSpinner.getValue().toString());
        LocalDateTime CTime = LocalDateTime.now();
        // Check
        if(Year > CTime.getYear()) ValidDate = true;
        else if(Year == CTime.getYear())
        {
            if(Month > CTime.getMonthValue()) ValidDate = true;
            else if(Month == CTime.getMonthValue())
            {
                if(Day > CTime.getDayOfMonth()) ValidDate = true;
                else if(Day == CTime.getDayOfMonth())
                {
                    if(Hour > CTime.getHour()) ValidDate = true;
                    else if(Hour == CTime.getHour())
                    {
                        if(Minute > CTime.getMinute()) ValidDate = true;
                    }
                }
            }
        }
        // Date as String
        String SelectedDateTime = Integer.toString(Year) + '-' + Integer.toString(Month) + '-' + Integer.toString(Day) + ' ' + Integer.toString(Hour) + ':' + Integer.toString(Minute);
        if(InputFlag && ValidDate)
        {
            // Push Data as New Task
            ArrayList<String> Infos = new ArrayList<>();
            Infos.add(TaskName); // Name
            Infos.add(SelectedDateTime); // DateTime
            Infos.add(TaskDesc); // Desc
            C.AddTask(TasksPane, Infos);
            // Clear Input
            javax.swing.JComboBox Date[] = new javax.swing.JComboBox[3];
            javax.swing.JSpinner Time[] = new javax.swing.JSpinner[3];
            Date[0] = MonthComboBox;
            Date[1] = DayComboBox;
            Date[2] = YearComboBox;
            Time[0] = HoursSpinner;
            Time[1] = MinutesSpinner;
            Time[2] = AMorPM;
            C.Clear(TaskNameField, TaskDescField, Date, Time, SpObj);
        }
        else
        {
            // Pop up
            String PopUpStr = "";
            if(!InputFlag)
            {
                PopUpStr += "Missing Input Error";
            }
            if(!ValidDate)
            {
                if(PopUpStr.length() > 0)
                {
                    PopUpStr += ", ";
                }
                PopUpStr += "Invalid Date Error";
            }
            JOptionPane.showMessageDialog(rootPane, PopUpStr);
        }
    }//GEN-LAST:event_AddTasksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            // Nimbus
            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    System.out.println(info.getClassName());
                    break;
                }
            }
            */
            // System
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
            
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            // Set New Look and Feel
        }
        //</editor-fold>
        
        
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AMorPM;
    private javax.swing.JButton AddTasksButton;
    private javax.swing.JPanel AddTasksTab;
    private javax.swing.JComboBox<String> DayComboBox;
    private javax.swing.JLabel DeadlineLabel;
    private javax.swing.JScrollPane DescScrollPane;
    private javax.swing.JSpinner HoursSpinner;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane MainScrollpane;
    private javax.swing.JSpinner MinutesSpinner;
    private javax.swing.JComboBox<String> MonthComboBox;
    private javax.swing.JTextArea TaskDescField;
    private javax.swing.JLabel TaskDescLabel;
    private javax.swing.JTextField TaskNameField;
    private javax.swing.JLabel TaskNameLabel;
    private javax.swing.JTabbedPane TasksPane;
    private javax.swing.JLabel TimeColonLabel;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JComboBox<String> YearComboBox;
    // End of variables declaration//GEN-END:variables
}
