/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tasks_update.task;

import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author trias
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates Frame
     */
    
    // Init
    Control C = new Control();
    Control.Files C_Files = C.new Files();
    Control.TasksTab C_Task = C.new TasksTab();
    Control.RolesAndAccountsTab C_RA = C.new RolesAndAccountsTab();
    
    public MainFrame()
    {
        initComponents();
        // Start
        C_Files.Init_File();
        C_Task.LoadTasks(TaskTabPane);
        C_RA.LoadRoles(RolesTable);
        C_RA.LoadAccounts(AccountsTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Roles = new javax.swing.JFrame();
        RoleMainPanel = new javax.swing.JPanel();
        RoleHeaderPanel = new javax.swing.JPanel();
        RoleTitle = new javax.swing.JLabel();
        RolesTabPane = new javax.swing.JTabbedPane();
        AddRole = new javax.swing.JPanel();
        EventLabel = new javax.swing.JLabel();
        RoleLabel = new javax.swing.JLabel();
        EventNameField = new javax.swing.JTextField();
        RoleNameField = new javax.swing.JTextField();
        AddRoleButton = new javax.swing.JButton();
        DeleteRole = new javax.swing.JPanel();
        EventRoleLabel = new javax.swing.JLabel();
        DeleteEventRoleComboBox = new javax.swing.JComboBox<>();
        DeleteRoleButton = new javax.swing.JButton();
        RoleReloadButton = new javax.swing.JButton();
        Accounts = new javax.swing.JFrame();
        AccountMainPanel = new javax.swing.JPanel();
        AccountHeaderPanel = new javax.swing.JPanel();
        AccountTitle = new javax.swing.JLabel();
        AccountsTabPane = new javax.swing.JTabbedPane();
        Accounts_AddAccount = new javax.swing.JPanel();
        SiteLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        AccountAddButton = new javax.swing.JButton();
        SiteChooseComboBox = new javax.swing.JComboBox<>();
        Accounts_DeleteAccount = new javax.swing.JPanel();
        DeleteAcctComboBox = new javax.swing.JComboBox<>();
        DeleteAccountLabel = new javax.swing.JLabel();
        AccountReloadButton = new javax.swing.JButton();
        DeleteAccountButton = new javax.swing.JButton();
        Accounts_LogIn = new javax.swing.JPanel();
        LogInAccountLabel = new javax.swing.JLabel();
        LogInAcctComboBox = new javax.swing.JComboBox<>();
        LogInReloadButton = new javax.swing.JButton();
        LogInAccountButton = new javax.swing.JButton();
        SampleTab = new javax.swing.JPanel();
        SampleTabTitle = new javax.swing.JLabel();
        DeadlineField = new javax.swing.JTextField();
        QWER = new javax.swing.JScrollPane();
        SampleTabArea = new javax.swing.JTextArea();
        Edit = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        DealineLabel = new javax.swing.JLabel();
        PriorityLvlLabel = new javax.swing.JLabel();
        PriorityLvl = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        MainTitle = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        MainScrollPane = new javax.swing.JScrollPane();
        MainTabPane = new javax.swing.JTabbedPane();
        TasksTab = new javax.swing.JPanel();
        TaskScrollPane = new javax.swing.JScrollPane();
        TaskTabPane = new javax.swing.JTabbedPane();
        AddNewTaskTab = new javax.swing.JPanel();
        AddTaskLabel = new javax.swing.JLabel();
        TaskNameLabel = new javax.swing.JLabel();
        TaskContentLabel = new javax.swing.JLabel();
        TaskDeadlineLabel = new javax.swing.JLabel();
        TaskContentScrollPane = new javax.swing.JScrollPane();
        TaskContentArea = new javax.swing.JTextArea();
        TaskNameField = new javax.swing.JTextField();
        TaskDeadlineChooser = new com.toedter.calendar.JDateChooser();
        SelectHour = new javax.swing.JSpinner();
        HourMinuteSeparator = new javax.swing.JLabel();
        SelectMinute = new javax.swing.JSpinner();
        SelectAMPM = new javax.swing.JComboBox<>();
        AddTaskButton = new javax.swing.JButton();
        TaskPriorityLabel = new javax.swing.JLabel();
        PrioritySpinner = new javax.swing.JSpinner();
        AccountsAndRolesTab = new javax.swing.JPanel();
        Separator = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        RolesPanel = new javax.swing.JPanel();
        RolesLabel = new javax.swing.JLabel();
        RolesScrollPane = new javax.swing.JScrollPane();
        RolesTable = new javax.swing.JTable();
        ManageRolesButton = new javax.swing.JButton();
        AccountsPanel = new javax.swing.JPanel();
        AccountsScrollPane = new javax.swing.JScrollPane();
        AccountsTable = new javax.swing.JTable();
        AccountsLabel = new javax.swing.JLabel();
        ManageAccountsButton = new javax.swing.JButton();
        About = new javax.swing.JPanel();
        UninstallLabel = new javax.swing.JLabel();
        UninstallButton = new javax.swing.JButton();
        AboutScrollPane = new javax.swing.JScrollPane();
        AboutTextArea = new javax.swing.JTextArea();

        Roles.setAlwaysOnTop(true);
        Roles.setResizable(false);
        Roles.setSize(new java.awt.Dimension(330, 400));

        RoleTitle.setFont(new java.awt.Font("Champagne & Limousines", 1, 36)); // NOI18N
        RoleTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoleTitle.setText("Roles");

        javax.swing.GroupLayout RoleHeaderPanelLayout = new javax.swing.GroupLayout(RoleHeaderPanel);
        RoleHeaderPanel.setLayout(RoleHeaderPanelLayout);
        RoleHeaderPanelLayout.setHorizontalGroup(
            RoleHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoleTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RoleHeaderPanelLayout.setVerticalGroup(
            RoleHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoleTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        EventLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        EventLabel.setText("Event Name:");

        RoleLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        RoleLabel.setText("Role Name:");

        EventNameField.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N

        RoleNameField.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N

        AddRoleButton.setFont(new java.awt.Font("Champagne & Limousines", 0, 18)); // NOI18N
        AddRoleButton.setText("Add Role");
        AddRoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddRoleLayout = new javax.swing.GroupLayout(AddRole);
        AddRole.setLayout(AddRoleLayout);
        AddRoleLayout.setHorizontalGroup(
            AddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddRoleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(AddRoleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddRoleLayout.createSequentialGroup()
                        .addComponent(EventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddRoleLayout.createSequentialGroup()
                        .addComponent(RoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RoleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        AddRoleLayout.setVerticalGroup(
            AddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRoleLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(AddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(AddRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        RolesTabPane.addTab("Add Role", AddRole);

        EventRoleLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        EventRoleLabel.setText("Event-Role:");

        DeleteEventRoleComboBox.setFont(new java.awt.Font("Champagne & Limousines", 0, 18)); // NOI18N

        DeleteRoleButton.setFont(new java.awt.Font("Champagne & Limousines", 0, 18)); // NOI18N
        DeleteRoleButton.setText("Delete Role");
        DeleteRoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRoleButtonActionPerformed(evt);
            }
        });

        RoleReloadButton.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        RoleReloadButton.setText("Reload");
        RoleReloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleReloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteRoleLayout = new javax.swing.GroupLayout(DeleteRole);
        DeleteRole.setLayout(DeleteRoleLayout);
        DeleteRoleLayout.setHorizontalGroup(
            DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRoleLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteRoleLayout.createSequentialGroup()
                        .addComponent(RoleReloadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(DeleteRoleButton))
                    .addGroup(DeleteRoleLayout.createSequentialGroup()
                        .addComponent(EventRoleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteEventRoleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        DeleteRoleLayout.setVerticalGroup(
            DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRoleLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteEventRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventRoleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleReloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        RolesTabPane.addTab("Delete Role", DeleteRole);

        javax.swing.GroupLayout RoleMainPanelLayout = new javax.swing.GroupLayout(RoleMainPanel);
        RoleMainPanel.setLayout(RoleMainPanelLayout);
        RoleMainPanelLayout.setHorizontalGroup(
            RoleMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoleHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RolesTabPane)
        );
        RoleMainPanelLayout.setVerticalGroup(
            RoleMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoleMainPanelLayout.createSequentialGroup()
                .addComponent(RoleHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RolesTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout RolesLayout = new javax.swing.GroupLayout(Roles.getContentPane());
        Roles.getContentPane().setLayout(RolesLayout);
        RolesLayout.setHorizontalGroup(
            RolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoleMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RolesLayout.setVerticalGroup(
            RolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoleMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Accounts.setPreferredSize(new java.awt.Dimension(327, 400));
        Accounts.setResizable(false);
        Accounts.setSize(new java.awt.Dimension(327, 400));

        AccountTitle.setFont(new java.awt.Font("Champagne & Limousines", 1, 36)); // NOI18N
        AccountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccountTitle.setText("Accounts");

        javax.swing.GroupLayout AccountHeaderPanelLayout = new javax.swing.GroupLayout(AccountHeaderPanel);
        AccountHeaderPanel.setLayout(AccountHeaderPanelLayout);
        AccountHeaderPanelLayout.setHorizontalGroup(
            AccountHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AccountHeaderPanelLayout.setVerticalGroup(
            AccountHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        AccountsTabPane.setFocusable(false);
        AccountsTabPane.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N

        SiteLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        SiteLabel.setText("Site:");

        UsernameLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        UsernameLabel.setText("Username:");

        PasswordLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        PasswordLabel.setText("Password:");

        UsernameField.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N

        PasswordField.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N

        AccountAddButton.setFont(new java.awt.Font("Champagne & Limousines", 0, 14)); // NOI18N
        AccountAddButton.setText("Add Account");
        AccountAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountAddButtonActionPerformed(evt);
            }
        });

        SiteChooseComboBox.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        SiteChooseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facebook", "Google", "Microsoft" }));

        javax.swing.GroupLayout Accounts_AddAccountLayout = new javax.swing.GroupLayout(Accounts_AddAccount);
        Accounts_AddAccount.setLayout(Accounts_AddAccountLayout);
        Accounts_AddAccountLayout.setHorizontalGroup(
            Accounts_AddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounts_AddAccountLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(Accounts_AddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accounts_AddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PasswordLabel)
                        .addComponent(UsernameLabel))
                    .addComponent(SiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(Accounts_AddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiteChooseComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Accounts_AddAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AccountAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        Accounts_AddAccountLayout.setVerticalGroup(
            Accounts_AddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounts_AddAccountLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Accounts_AddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteLabel)
                    .addComponent(SiteChooseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Accounts_AddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Accounts_AddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(AccountAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        AccountsTabPane.addTab("Add Account", Accounts_AddAccount);

        DeleteAcctComboBox.setFont(new java.awt.Font("Champagne & Limousines", 0, 18)); // NOI18N

        DeleteAccountLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        DeleteAccountLabel.setText("Account:");

        AccountReloadButton.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        AccountReloadButton.setText("Reload");
        AccountReloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountReloadButtonActionPerformed(evt);
            }
        });

        DeleteAccountButton.setFont(new java.awt.Font("Champagne & Limousines", 0, 18)); // NOI18N
        DeleteAccountButton.setText("Delete Account");
        DeleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Accounts_DeleteAccountLayout = new javax.swing.GroupLayout(Accounts_DeleteAccount);
        Accounts_DeleteAccount.setLayout(Accounts_DeleteAccountLayout);
        Accounts_DeleteAccountLayout.setHorizontalGroup(
            Accounts_DeleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounts_DeleteAccountLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Accounts_DeleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accounts_DeleteAccountLayout.createSequentialGroup()
                        .addComponent(AccountReloadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(DeleteAccountButton))
                    .addGroup(Accounts_DeleteAccountLayout.createSequentialGroup()
                        .addComponent(DeleteAccountLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteAcctComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        Accounts_DeleteAccountLayout.setVerticalGroup(
            Accounts_DeleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounts_DeleteAccountLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(Accounts_DeleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteAcctComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteAccountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(Accounts_DeleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountReloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        AccountsTabPane.addTab("Delete Account", Accounts_DeleteAccount);

        LogInAccountLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        LogInAccountLabel.setText("Account:");

        LogInAcctComboBox.setFont(new java.awt.Font("Champagne & Limousines", 0, 18)); // NOI18N

        LogInReloadButton.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        LogInReloadButton.setText("Reload");
        LogInReloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInReloadButtonActionPerformed(evt);
            }
        });

        LogInAccountButton.setFont(new java.awt.Font("Champagne & Limousines", 0, 18)); // NOI18N
        LogInAccountButton.setText("LogIn Account");
        LogInAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Accounts_LogInLayout = new javax.swing.GroupLayout(Accounts_LogIn);
        Accounts_LogIn.setLayout(Accounts_LogInLayout);
        Accounts_LogInLayout.setHorizontalGroup(
            Accounts_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounts_LogInLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Accounts_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accounts_LogInLayout.createSequentialGroup()
                        .addComponent(LogInReloadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(LogInAccountButton))
                    .addGroup(Accounts_LogInLayout.createSequentialGroup()
                        .addComponent(LogInAccountLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LogInAcctComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        Accounts_LogInLayout.setVerticalGroup(
            Accounts_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounts_LogInLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(Accounts_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInAcctComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogInAccountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(Accounts_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogInReloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        AccountsTabPane.addTab("Log In", Accounts_LogIn);

        javax.swing.GroupLayout AccountMainPanelLayout = new javax.swing.GroupLayout(AccountMainPanel);
        AccountMainPanel.setLayout(AccountMainPanelLayout);
        AccountMainPanelLayout.setHorizontalGroup(
            AccountMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AccountsTabPane)
        );
        AccountMainPanelLayout.setVerticalGroup(
            AccountMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountMainPanelLayout.createSequentialGroup()
                .addComponent(AccountHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccountsTabPane))
        );

        javax.swing.GroupLayout AccountsLayout = new javax.swing.GroupLayout(Accounts.getContentPane());
        Accounts.getContentPane().setLayout(AccountsLayout);
        AccountsLayout.setHorizontalGroup(
            AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AccountsLayout.setVerticalGroup(
            AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        SampleTabTitle.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        SampleTabTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SampleTabTitle.setText("__ Sample Tab __");

        DeadlineField.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        DeadlineField.setText("Deadline");

        SampleTabArea.setColumns(20);
        SampleTabArea.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        SampleTabArea.setRows(5);
        QWER.setViewportView(SampleTabArea);

        Edit.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        Edit.setText("Edit Task");

        Remove.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        Remove.setText("Remove Task");

        DealineLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        DealineLabel.setText("Deadline:");

        PriorityLvlLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        PriorityLvlLabel.setText("Prority Lvl:");

        PriorityLvl.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        PriorityLvl.setText("N");

        javax.swing.GroupLayout SampleTabLayout = new javax.swing.GroupLayout(SampleTab);
        SampleTab.setLayout(SampleTabLayout);
        SampleTabLayout.setHorizontalGroup(
            SampleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SampleTabLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(SampleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QWER, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SampleTabLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(Edit)
                        .addGap(106, 106, 106)
                        .addComponent(Remove))
                    .addGroup(SampleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SampleTabLayout.createSequentialGroup()
                            .addComponent(DealineLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DeadlineField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PriorityLvlLabel)
                            .addGap(18, 18, 18)
                            .addComponent(PriorityLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SampleTabLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(SampleTabTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        SampleTabLayout.setVerticalGroup(
            SampleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SampleTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(SampleTabTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SampleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PriorityLvlLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PriorityLvl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SampleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeadlineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DealineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(QWER, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SampleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edit)
                    .addComponent(Remove))
                .addGap(36, 36, 36))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Task");
        setResizable(false);

        MainTitle.setFont(new java.awt.Font("Champagne & Limousines", 0, 36)); // NOI18N
        MainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainTitle.setText("Task");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        MainScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        MainScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        MainTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        MainTabPane.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N

        TaskScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TaskScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TaskTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TaskTabPane.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N

        AddTaskLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        AddTaskLabel.setText("Add New Task");

        TaskNameLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        TaskNameLabel.setText("Task Name:");

        TaskContentLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        TaskContentLabel.setText("Task Content:");

        TaskDeadlineLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        TaskDeadlineLabel.setText("Task Deadline:");

        TaskContentArea.setColumns(20);
        TaskContentArea.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        TaskContentArea.setRows(5);
        TaskContentScrollPane.setViewportView(TaskContentArea);

        TaskNameField.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        TaskNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskNameFieldActionPerformed(evt);
            }
        });

        TaskDeadlineChooser.setDateFormatString("MMM d y");
        TaskDeadlineChooser.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N

        SelectHour.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N
        SelectHour.setModel(new javax.swing.SpinnerNumberModel(6, 1, 12, 1));

        HourMinuteSeparator.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        HourMinuteSeparator.setText(":");

        SelectMinute.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N
        SelectMinute.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"}));

        SelectAMPM.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N
        SelectAMPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        SelectAMPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAMPMActionPerformed(evt);
            }
        });

        AddTaskButton.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        AddTaskButton.setText("Add Task");
        AddTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskButtonActionPerformed(evt);
            }
        });

        TaskPriorityLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        TaskPriorityLabel.setText("Priority Level:");

        PrioritySpinner.setFont(new java.awt.Font("Champagne & Limousines", 1, 14)); // NOI18N
        PrioritySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        javax.swing.GroupLayout AddNewTaskTabLayout = new javax.swing.GroupLayout(AddNewTaskTab);
        AddNewTaskTab.setLayout(AddNewTaskTabLayout);
        AddNewTaskTabLayout.setHorizontalGroup(
            AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewTaskTabLayout.createSequentialGroup()
                .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddNewTaskTabLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(AddTaskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddNewTaskTabLayout.createSequentialGroup()
                            .addGap(215, 215, 215)
                            .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TaskContentScrollPane)
                                .addComponent(TaskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddNewTaskTabLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddNewTaskTabLayout.createSequentialGroup()
                                    .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TaskNameLabel)
                                        .addComponent(TaskContentLabel))
                                    .addGap(323, 323, 323))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TaskPriorityLabel)
                                    .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AddNewTaskTabLayout.createSequentialGroup()
                                            .addGap(154, 154, 154)
                                            .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TaskDeadlineChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(AddNewTaskTabLayout.createSequentialGroup()
                                                    .addComponent(SelectHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(HourMinuteSeparator)
                                                    .addGap(10, 10, 10)
                                                    .addComponent(SelectMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(SelectAMPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(AddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PrioritySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddNewTaskTabLayout.createSequentialGroup()
                                            .addComponent(TaskDeadlineLabel)
                                            .addGap(323, 323, 323))))))))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        AddNewTaskTabLayout.setVerticalGroup(
            AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewTaskTabLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(AddTaskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskNameLabel)
                    .addComponent(TaskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskContentLabel)
                    .addComponent(TaskContentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskDeadlineLabel)
                    .addComponent(TaskDeadlineChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectAMPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HourMinuteSeparator)
                    .addComponent(SelectHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(AddNewTaskTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskPriorityLabel)
                    .addComponent(PrioritySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddTaskButton)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        TaskTabPane.addTab("__ Add Task __", AddNewTaskTab);

        TaskScrollPane.setViewportView(TaskTabPane);

        javax.swing.GroupLayout TasksTabLayout = new javax.swing.GroupLayout(TasksTab);
        TasksTab.setLayout(TasksTabLayout);
        TasksTabLayout.setHorizontalGroup(
            TasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TasksTabLayout.createSequentialGroup()
                .addComponent(TaskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1172, Short.MAX_VALUE))
        );
        TasksTabLayout.setVerticalGroup(
            TasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TasksTabLayout.createSequentialGroup()
                .addComponent(TaskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 238, Short.MAX_VALUE))
        );

        MainTabPane.addTab("Tasks", TasksTab);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        RolesLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 24)); // NOI18N
        RolesLabel.setText("Roles");

        RolesTable.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N
        RolesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event", "Role(s)"
            }
        ));
        RolesScrollPane.setViewportView(RolesTable);

        ManageRolesButton.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        ManageRolesButton.setText("Manage Roles");
        ManageRolesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageRolesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RolesPanelLayout = new javax.swing.GroupLayout(RolesPanel);
        RolesPanel.setLayout(RolesPanelLayout);
        RolesPanelLayout.setHorizontalGroup(
            RolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RolesPanelLayout.createSequentialGroup()
                .addGroup(RolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RolesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RolesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RolesPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageRolesButton)
                        .addGap(154, 154, 154)))
                .addComponent(RolesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        RolesPanelLayout.setVerticalGroup(
            RolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RolesPanelLayout.createSequentialGroup()
                .addGroup(RolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RolesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RolesLabel)
                        .addGap(48, 48, 48)
                        .addComponent(ManageRolesButton))
                    .addGroup(RolesPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(RolesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        AccountsTable.setFont(new java.awt.Font("Champagne & Limousines", 1, 12)); // NOI18N
        AccountsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Site", "Username", "Password"
            }
        ));
        AccountsScrollPane.setViewportView(AccountsTable);

        AccountsLabel.setFont(new java.awt.Font("Champagne & Limousines", 1, 24)); // NOI18N
        AccountsLabel.setText("Accounts");

        ManageAccountsButton.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        ManageAccountsButton.setText("Manage Accounts");
        ManageAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccountsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccountsPanelLayout = new javax.swing.GroupLayout(AccountsPanel);
        AccountsPanel.setLayout(AccountsPanelLayout);
        AccountsPanelLayout.setHorizontalGroup(
            AccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountsPanelLayout.createSequentialGroup()
                .addGroup(AccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AccountsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountsPanelLayout.createSequentialGroup()
                        .addContainerGap(73, Short.MAX_VALUE)
                        .addComponent(ManageAccountsButton)
                        .addGap(145, 145, 145)))
                .addComponent(AccountsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        AccountsPanelLayout.setVerticalGroup(
            AccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountsPanelLayout.createSequentialGroup()
                .addGroup(AccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountsPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(AccountsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AccountsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AccountsLabel)
                        .addGap(75, 75, 75)
                        .addComponent(ManageAccountsButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AccountsAndRolesTabLayout = new javax.swing.GroupLayout(AccountsAndRolesTab);
        AccountsAndRolesTab.setLayout(AccountsAndRolesTabLayout);
        AccountsAndRolesTabLayout.setHorizontalGroup(
            AccountsAndRolesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountsAndRolesTabLayout.createSequentialGroup()
                .addGroup(AccountsAndRolesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(RolesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccountsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Separator))
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1057, Short.MAX_VALUE))
        );
        AccountsAndRolesTabLayout.setVerticalGroup(
            AccountsAndRolesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountsAndRolesTabLayout.createSequentialGroup()
                .addComponent(RolesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccountsAndRolesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountsAndRolesTabLayout.createSequentialGroup()
                        .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        MainTabPane.addTab("Accounts and Roles", AccountsAndRolesTab);

        UninstallLabel.setFont(new java.awt.Font("Champagne & Limousines", 0, 24)); // NOI18N
        UninstallLabel.setText("Press this button to UNINSTALL this App");

        UninstallButton.setFont(new java.awt.Font("Champagne & Limousines", 1, 24)); // NOI18N
        UninstallButton.setText("Uninstall");
        UninstallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UninstallButtonActionPerformed(evt);
            }
        });

        AboutTextArea.setColumns(20);
        AboutTextArea.setFont(new java.awt.Font("Champagne & Limousines", 0, 18)); // NOI18N
        AboutTextArea.setRows(5);
        AboutTextArea.setText("This is the 3rd Version of Task App\n\n------------------------------------------------------------------------------------------------------\n\nCheck out my other repositories:\nhttps://github.com/DeathAscend001\n\n:)");
        AboutTextArea.setWrapStyleWord(true);
        AboutScrollPane.setViewportView(AboutTextArea);

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addGroup(AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(UninstallLabel))
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(UninstallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AboutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1182, Short.MAX_VALUE))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AboutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UninstallLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UninstallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        MainTabPane.addTab("About", About);

        MainScrollPane.setViewportView(MainTabPane);

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskButtonActionPerformed
        // TODO add your handling code here:
        // Get Task Name and Task Content
        String TaskName = TaskNameField.getText().trim();
        String TaskContent = TaskContentArea.getText().trim();
        // Get Date and Time
        Date date = TaskDeadlineChooser.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        String TaskDate = formatter.format(date);
        String TaskTime = SelectHour.getValue().toString() + ":" + SelectMinute.getValue().toString() + " " + SelectAMPM.getSelectedItem().toString();
        String TaskDateTime = String.join(" ", TaskDate, TaskTime);
        // // Get Priority // //
        String TaskPriority = PrioritySpinner.getValue().toString();
        // Check Inputs
        if(C_Task.TaskErrorCheck(new ArrayList<>(List.of(TaskName, TaskDateTime, TaskContent))))
        {
            // Push to Task
            C_Task.ModifyTask(new ArrayList<>(List.of(TaskName, TaskDateTime, TaskPriority, TaskContent)), TaskTabPane, '+');
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Error Making Task, Check Your Details Again");
        }
    }//GEN-LAST:event_AddTaskButtonActionPerformed

    private void SelectAMPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAMPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectAMPMActionPerformed

    private void ManageRolesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageRolesButtonActionPerformed
        // TODO add your handling code here:
        Roles.setVisible(true);
        Roles.setLocationRelativeTo(null);
    }//GEN-LAST:event_ManageRolesButtonActionPerformed

    private void ManageAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccountsButtonActionPerformed
        // TODO add your handling code here:
        Accounts.setVisible(true);
        Accounts.setLocationRelativeTo(null);
    }//GEN-LAST:event_ManageAccountsButtonActionPerformed

    private void TaskNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskNameFieldActionPerformed

    private void UninstallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UninstallButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(rootPane, "You could do a manual uninstallation of this app!");
        javax.swing.JOptionPane.showMessageDialog(rootPane, "Do NOT Open This App after uninstallation or folders will be regenerated!");
        // Uninstall File
        C_Files.Uninstall();
    }//GEN-LAST:event_UninstallButtonActionPerformed

    private void AddRoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoleButtonActionPerformed
        // TODO add your handling code here:
        // Get Inputs From TextFields
        String EventName = EventNameField.getText();
        String RoleName = RoleNameField.getText();
        // Check Inputs
        if(C_RA.RoleErrorCheck(EventName, RoleName))
        {
            // Push To Final
            C_RA.ModifyRoles(new ArrayList<>(List.of(EventName, RoleName)), RolesTable, '+');
        }
        else
        {
            JOptionPane.showMessageDialog(Roles, "Cannot Add Role!");
        }
    }//GEN-LAST:event_AddRoleButtonActionPerformed

    private void DeleteRoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRoleButtonActionPerformed
        // TODO add your handling code here:
        // Get Inputs From ComboBox
        String EventRoleName = DeleteEventRoleComboBox.getSelectedItem().toString();
        // Push To Final
        C_RA.ModifyRoles(new ArrayList<>(List.of(EventRoleName)), RolesTable, '-');
    }//GEN-LAST:event_DeleteRoleButtonActionPerformed

    private void RoleReloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleReloadButtonActionPerformed
        // TODO add your handling code here:
        C_RA.RoleRefresh_RDeleteCustom(DeleteEventRoleComboBox);
    }//GEN-LAST:event_RoleReloadButtonActionPerformed

    private void AccountReloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountReloadButtonActionPerformed
        // TODO add your handling code here:
        C_RA.AccountRefresh_ALogInDeleteCustom(DeleteAcctComboBox);
    }//GEN-LAST:event_AccountReloadButtonActionPerformed

    private void DeleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountButtonActionPerformed
        // TODO add your handling code here:
        C_RA.ModifyAccount(new ArrayList<>(List.of(DeleteAcctComboBox.getSelectedItem().toString())), AccountsTable, '-');
    }//GEN-LAST:event_DeleteAccountButtonActionPerformed

    private void LogInReloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInReloadButtonActionPerformed
        // TODO add your handling code here:
        C_RA.AccountRefresh_ALogInDeleteCustom(LogInAcctComboBox);
    }//GEN-LAST:event_LogInReloadButtonActionPerformed

    private void LogInAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInAccountButtonActionPerformed
        // TODO add your handling code here:
        C_RA.AccountLogIn(LogInAcctComboBox.getSelectedItem().toString(), Accounts);
    }//GEN-LAST:event_LogInAccountButtonActionPerformed

    private void AccountAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountAddButtonActionPerformed
        // TODO add your handling code here:
        // Get Inputs
        String SiteName = SiteChooseComboBox.getSelectedItem().toString();
        String UserName = UsernameField.getText();
        String PassName = PasswordField.getText();
        // Check Inputs
        if(C_RA.AccountErrorCheck(SiteName, UserName, PassName))
        {
            // Push To Final
            C_RA.ModifyAccount(new ArrayList<>(List.of(SiteName, UserName, PassName)), AccountsTable, '+');
        }
        else
        {
            JOptionPane.showMessageDialog(Roles, "Cannot Add Account!");
        }
    }//GEN-LAST:event_AccountAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaF look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatLaf is not available, stay with the default look and feel.
         */
        try
        {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JScrollPane AboutScrollPane;
    private javax.swing.JTextArea AboutTextArea;
    private javax.swing.JButton AccountAddButton;
    private javax.swing.JPanel AccountHeaderPanel;
    private javax.swing.JPanel AccountMainPanel;
    private javax.swing.JButton AccountReloadButton;
    private javax.swing.JLabel AccountTitle;
    private javax.swing.JFrame Accounts;
    private javax.swing.JPanel AccountsAndRolesTab;
    private javax.swing.JLabel AccountsLabel;
    private javax.swing.JPanel AccountsPanel;
    private javax.swing.JScrollPane AccountsScrollPane;
    private javax.swing.JTabbedPane AccountsTabPane;
    private javax.swing.JTable AccountsTable;
    private javax.swing.JPanel Accounts_AddAccount;
    private javax.swing.JPanel Accounts_DeleteAccount;
    private javax.swing.JPanel Accounts_LogIn;
    private javax.swing.JPanel AddNewTaskTab;
    private javax.swing.JPanel AddRole;
    private javax.swing.JButton AddRoleButton;
    private javax.swing.JButton AddTaskButton;
    private javax.swing.JLabel AddTaskLabel;
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JTextField DeadlineField;
    private javax.swing.JLabel DealineLabel;
    private javax.swing.JButton DeleteAccountButton;
    private javax.swing.JLabel DeleteAccountLabel;
    private javax.swing.JComboBox<String> DeleteAcctComboBox;
    private javax.swing.JComboBox<String> DeleteEventRoleComboBox;
    private javax.swing.JPanel DeleteRole;
    private javax.swing.JButton DeleteRoleButton;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel EventLabel;
    private javax.swing.JTextField EventNameField;
    private javax.swing.JLabel EventRoleLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel HourMinuteSeparator;
    private javax.swing.JButton LogInAccountButton;
    private javax.swing.JLabel LogInAccountLabel;
    private javax.swing.JComboBox<String> LogInAcctComboBox;
    private javax.swing.JButton LogInReloadButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane MainScrollPane;
    private javax.swing.JTabbedPane MainTabPane;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JButton ManageAccountsButton;
    private javax.swing.JButton ManageRolesButton;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PriorityLvl;
    private javax.swing.JLabel PriorityLvlLabel;
    private javax.swing.JSpinner PrioritySpinner;
    private javax.swing.JScrollPane QWER;
    private javax.swing.JButton Remove;
    private javax.swing.JPanel RoleHeaderPanel;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JPanel RoleMainPanel;
    private javax.swing.JTextField RoleNameField;
    private javax.swing.JButton RoleReloadButton;
    private javax.swing.JLabel RoleTitle;
    private javax.swing.JFrame Roles;
    private javax.swing.JLabel RolesLabel;
    private javax.swing.JPanel RolesPanel;
    private javax.swing.JScrollPane RolesScrollPane;
    private javax.swing.JTabbedPane RolesTabPane;
    private javax.swing.JTable RolesTable;
    private javax.swing.JPanel SampleTab;
    private javax.swing.JTextArea SampleTabArea;
    private javax.swing.JLabel SampleTabTitle;
    private javax.swing.JComboBox<String> SelectAMPM;
    private javax.swing.JSpinner SelectHour;
    private javax.swing.JSpinner SelectMinute;
    private javax.swing.JSeparator Separator;
    private javax.swing.JComboBox<String> SiteChooseComboBox;
    private javax.swing.JLabel SiteLabel;
    private javax.swing.JTextArea TaskContentArea;
    private javax.swing.JLabel TaskContentLabel;
    private javax.swing.JScrollPane TaskContentScrollPane;
    private com.toedter.calendar.JDateChooser TaskDeadlineChooser;
    private javax.swing.JLabel TaskDeadlineLabel;
    private javax.swing.JTextField TaskNameField;
    private javax.swing.JLabel TaskNameLabel;
    private javax.swing.JLabel TaskPriorityLabel;
    private javax.swing.JScrollPane TaskScrollPane;
    private javax.swing.JTabbedPane TaskTabPane;
    private javax.swing.JPanel TasksTab;
    private javax.swing.JButton UninstallButton;
    private javax.swing.JLabel UninstallLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
